services:
  db:
    image: postgres:16-alpine
    container_name: financial-db
    environment:
      POSTGRES_DB: financial_organization
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d financial_organization"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: financial-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker

      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/financial_organization

      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH: ${JWT_REFRESH}
      JWT_REFRESH_REMEMBER_ME: ${JWT_REFRESH_REMEMBER_ME}
      REMEMBER_KEY: ${REMEMBER_KEY}
      COOKIE_MAX: ${COOKIE_MAX}

      FASTFOREX_KEY: ${FASTFOREX_KEY}
      FASTFOREX: ${FASTFOREX}
      COINGECKO: ${COINGECKO}
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
